services:
    _defaults:
        bind:
            $ticketingTemplates: '%ticketing.templates%'

    Maps_red\TicketingBundle\Controller\:
        resource: '../../Controller'
        autowire: true
        tags: ['controller.service_arguments']

    Maps_red\TicketingBundle\Form\:
        resource: '../../Form'
        tags: ['form.type']

    Maps_red\TicketingBundle\Utils\:
        resource: '../../Utils'
        autowire: true

    Maps_red\TicketingBundle\Maker\MakeTicketing:
        arguments: ["@maker.file_manager"]
        tags:
            - { name: maker.command }

    Maps_red\TicketingBundle\Manager\TicketManager:
        tags:
            -
              name: ticketing.manager
              class: 'ticket'
              enable_history: true
              enable_ticket_restriction: true
              restricted_tickets_role: true

    Maps_red\TicketingBundle\Manager\TicketCategoryManager:
        tags:
            - { name: ticketing.manager, class: 'ticket_category'}

    Maps_red\TicketingBundle\Manager\TicketCommentManager:
        tags:
            - { name: ticketing.manager, class: 'ticket_comment'}

    Maps_red\TicketingBundle\Manager\TicketHistoryManager:
        tags:
            - { name: ticketing.manager, class: 'ticket_history'}

    Maps_red\TicketingBundle\Manager\TicketKeywordManager:
        tags:
            - { name: ticketing.manager, class: 'ticket_keyword'}

    Maps_red\TicketingBundle\Manager\TicketStatusManager:
        tags:
            - { name: ticketing.manager, class: 'ticket_status', ticket_status: true }

    Maps_red\TicketingBundle\Manager\TicketPriorityManager:
        tags:
            - { name: ticketing.manager, class: 'ticket_priority'}

    Maps_red\TicketingBundle\Manager\TicketStatusHistoryManager:
        tags:
            - { name: ticketing.manager, class: 'ticket_status_history'}

    Maps_red\TicketingBundle\EventSubscriber\RequestSubscriber:
        autowire: true
        tags:
            - { name: kernel.event_subscriber }

    Maps_red\TicketingBundle\EventSubscriber\TicketHistorySubscriber:
        autowire: true
        arguments:
            $enableHistory: "%ticketing.enable_history%"
        tags:
            - { name: kernel.event_subscriber }

    Maps_red\TicketingBundle\EventSubscriber\TicketStatusHistorySubscriber:
        autowire: true
        tags:
            - { name: kernel.event_subscriber }

    Maps_red\TicketingBundle\EventSubscriber\TicketDoctrineSubscriber:
        arguments: ['@event_dispatcher']
        tags:
            - { name: doctrine.event_subscriber, connection: default }

    Maps_red\TicketingBundle\Twig\TicketingExtension:
        arguments: ["%ticketing.templates%", "%ticketing.stylesheets%", "%ticketing.javascripts%"]
        autowire: true
        tags:
            - { name: twig.extension }